# comment
map_path: "map/simple01.json"

vehicle:
  length: 4.7
  width: 2.1
  wheelbase: 2.8
  rear_to_center: 1.4
  max_steer: 0.7

hybrid_astar:
  xy_resolution: 0.5
  theta_bins: 180
  step_size: 0.1
  primitive_length: 1.0
  goal_xy_tolerance: 0.8
  goal_theta_tolerance: 0.15
  reverse_penalty: 1.5
  steer_penalty: 0.2
  gear_switch_penalty: 2.0
  steer_change_penalty: 0.3
  max_iterations: 42
  allow_reverse: yes
  enable_analytic_expansion: 0
  analytic_expansion_distance: 10.5
  analytic_expansion_interval: 3
  collision_safety_margin: 0.05
  enable_obstacle_heuristic: true
  obstacle_heuristic_inflate_alpha: 1.25
  debug: no
  debug_progress_interval: 7
